version: '3'
services:
  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      # - ./web:/
      - "./:/var/www/html"
      - ./site.conf:/etc/nginx/conf.d/default.conf
    environment:
          - NGINX_HOST=nginx
    # command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php

  php:
    image: nanoninja/php-fpm:7.2.15
    volumes:
        - "./:/var/www/html"
        - ./php.ini:/usr/local/etc/php/conf.d/php.ini"
        - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  composer:
    image: "composer"
    volumes:
        - "./:/app"
    command: install
    